sudo: required
services:
    - docker

script:
    - docker build -t johnboyleeds/node .
    - docker images johnboyleeds/node

before_deploy:
    - echo "$988oBsQI6" | docker login -u "johnboyleeds" --password-stdin

deploy:
    provider: script
    script: docker push johnboyleeds/node
    on:
        branch: master
       