sudo: required
services:
    - docker

script:
    - docker build -t johnboyleeds/node .
    - docker images johnboyleeds/node

before_deploy:
    - echo "5723331c-e4fe-4cfe-96c8-9a6e449283ff" | docker login -u "johnboyleeds" --password-stdin

deploy:
    provider: script
    script: docker push johnboyleeds/node
    on:
        branch: master
       