sudo: required
services:
    - docker

script:
    - docker build -t johnboyleeds/node .
    - docker images johnboyleeds/node

before_deploy:
    - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin

deploy:
    provider: script
    script: docker push johnboyleeds/node
    on:
        branch: master
       