sudo: required
services:
    - docker

script:
    - docker build -t johnboyleeds/node .
    - docker images johnboyleeds/node

before_deploy:
    - docker login -u $DOCKER_USER -p $DOCKER_PASS

deploy:
    provider: script
    script: docker push johnboyleeds/node
    on:
        branch: master
       